### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jige003** [zommiommy/cache_decorator#13]
I set param `validity_duration` and sometimes raise the `FileNotFoundError` exception:

```log
Traceback (most recent call last):

File "/Users/xx/anaconda3/lib/python3.8/site-packages/cache_decorator/cache.py", line 605, in wrapped
    result = self._load(path)
  File "/Users/xx/anaconda3/lib/python3.8/site-packages/cache_decorator/cache.py", line 476, in _load
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: 
```

**Comment by zommiommy** [comment]
Hi! Thanks for opening this Issue, can you share a little script to reproduce this error?
This way I can add it to the test_suite.

**Comment by jige003** [comment]
Most of the time it's normal, but occasionally it triggers

My code
```python
class XCache(Cache):
    """cache_decorator rewrite cache dir """

    def __init__(self, *args, **kwargs):
        super(XCache, self).__init__(
            cache_dir=str(CACHE_DECORATOR_DIR), *args, **kwargs
        )

@XCache(validity_duration="1h")
def get_xxx_cache():
     ....
```

**Comment by zommiommy** [comment]
Hi! Sorry for the delay, your pull request seems reasonable. This is a significant improvement because that's a possible datarace. 

I've pushed version 2.1.12 including your changes.

Thanks Again 😊
